### ISSUE TITLE
Práctica de Test Case

### ISSUE THREAD

**Issue by Anthony4523** [SistemasTecTlaxiaco/practica-de-test-case-entrevista-Prestadores-de-servicio#1]
[Práctica Test Case.pdf](https://github.com/SistemasTecTlaxiaco/practica-de-test-case-entrevista-Prestadores-de-servicio/files/7345078/Practica.Test.Case.pdf)

**Comment by Edwin-1012** [comment]
Calificación: 20%.
Contiene los puntos necesarios o requeridos para cumplir con la práctica.

**Comment by josealfredo79** [comment]
Esta bien hecho y revisado.
